### ISSUE TITLE
Building on Archlinux (it works)

### ISSUE THREAD

**Issue by NicolasCARPi** [DanielSunday/bounce#3]
Hello,

You should add to the documentation that portaudio is needed. Here is what I need to do to satisfy dependencies on an Archlinux machine : 

``` sh
# pacman -Sy glfw portaudio
```

Also, it would be better to skip to next level directly instead of having to input it manually ;)

Keep making open source games !

Cheers,
~Nico

**Comment by DanielSunday** [comment]
Thank you for your suggestion. Portaudio is now mentioned in the README.
